- name: Recursively change ownership of a /opt/joueur
  file:
    path: /opt/joueur
    state: directory
    recurse: yes
    owner: "{{user}}"
    
- name: Recursively change ownership of a /opt/cerveau
  file:
    path: /opt/cerveau
    state: directory
    recurse: yes
    owner: "{{user}}"

- name: Recursively change ownership of a /opt/pyrena
  file:
    path: /opt/pyrena
    state: directory
    recurse: yes
    owner: "{{user}}"
    